### ISSUE TITLE
More banner preferences

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/hourglass#114]

**Comment by ksjdragon** [comment]
Most people dont' use their google plus profile, so i think we should just keep our one banner thing for now

**Comment by yamanq** [comment]
There have been requests to allow customization of the banner, and this is the simplest way

**Comment by ksjdragon** [comment]
And who's gonna customize their banner through google plus

**Comment by yamanq** [comment]
We are using google+ for the avatar, so it makes sense to do it for the banner as well. Additionally, users will have no reason to complain if there is a way to customize.

**Comment by ksjdragon** [comment]
Banner will most likely be eliminated, so this is no longer an issue
