### ISSUE TITLE
Phone apps with /mobile page

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/hourglass#40]
https://developer.android.com/guide/webapps/index.html
http://phonegap.com/

**Comment by yamanq** [comment]
https://www.meteor.com/tutorials/blaze/running-on-mobile

**Comment by ksjdragon** [comment]
Build it like the gmail app.

**Comment by ksjdragon** [comment]
1de03bdde17cd4b636349cf00bd31b3957cd4e77
