### ISSUE TITLE
Do something with reports/confirmations

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/hourglass#61]

**Comment by yamanq** [comment]
What should we do with this?

**Comment by yamanq** [comment]
Color in certain way if above certain ratio of reports:confirmations, with a minimum number of reports as well. Client side only

**Comment by ksjdragon** [comment]
Minimum amount of reports should be in preference, I think. And we need to sort work by date, if we don't already do so.

**Comment by ksjdragon** [comment]
What else should we have?
