### ISSUE TITLE
Does school have to be a required value for a class? (Add valid school checking?)

### ISSUE THREAD

**Issue by ksjdragon** [ksjdragon/hourglass#68]
![image](https://cloud.githubusercontent.com/assets/8921294/18114926/24ade038-6f09-11e6-920e-fa8dd84018fb.png)
![image](https://cloud.githubusercontent.com/assets/8921294/18117046/35499016-6f1a-11e6-90a2-85197b7a0fdb.png)

**Comment by ksjdragon** [comment]
I verified this with several other functions, and only editProfile seems to have this

**Comment by ksjdragon** [comment]
Exception is actually "throw 'Unauthorized'" For the console to actually return an error, you have to do "throw new Meteor.Error("stuff happened")" (you should probably change them to that, so we get actual readable errors)I think this is because if there are no schools, it doesn't allow you to create a class. Do we actually want a class to have a school?

**Comment by yamanq** [comment]
With the introduction of #71 , is removing the check for school still necessary?
