### ISSUE TITLE
manage classes on two lines when creating class due to scrollbar

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/hourglass#8]
![image](https://cloud.githubusercontent.com/assets/8166212/17530334/17f04086-5e45-11e6-98f5-e3d2eed13c91.png)

**Comment by ksjdragon** [comment]
Should no longer be issue

**Comment by yamanq** [comment]
Still an issue
![image](https://cloud.githubusercontent.com/assets/8166212/17535339/f2fec358-5e5b-11e6-9a37-12facaae6d11.png)

**Comment by ksjdragon** [comment]
Things will be moved, no longer an issue.
