### ISSUE TITLE
Cannot submit comments

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/hourglass#81]
After pressing submit, the field is cleared with no other changes. Further investigation into the work collection reveals that the comment was not added to the collection. "Characters Remaining" number remains the same until user exits work and re-enters.

**Comment by yamanq** [comment]
no console or server errors

**Comment by yamanq** [comment]
No errors in client and server consoles

**Comment by ksjdragon** [comment]
9d82b5e4afe0f381a203e093481df68b466f3022

**Comment by yamanq** [comment]
Not fixed

**Comment by yamanq** [comment]
Using new classes fixes this issue
