### ISSUE TITLE
Reorder classes, drag and drop

### ISSUE THREAD

**Issue by ksjdragon** [ksjdragon/hourglass#89]

**Comment by ksjdragon** [comment]
`'reorderClasses': function(newOrder) {
        var current = Meteor.user().profile;
        var hasAll = true;
        for(var i = 0; i < current.length; i++) {
            if(!_.contains(newOrder, current[i])) hasAll = false;
        }
        if(current.length === newOrder.length && hasAll) {
            current.classes = newOrder;
             Meteor.users.update({
                _id: Meteor.userId()
            }, {
                $set: {
                    profile: current
                }
            });
        } else {
            throw new Meteor.Error("unauthorized", "You are not authorized to complete this action.");
        }
    }`

This is my proposed server function for reordering. If I missed anything, feel free to change, or just not use it

**Comment by yamanq** [comment]
454ea15acbf669189507e3378bb0e49c0024f21b

**Comment by yamanq** [comment]
305556222ee0fdb6b203a42295cf008944b84b8b
