### ISSUE TITLE
Admin Upgrade

### ISSUE THREAD

**Issue by yamanq** [ksjdragon/hourglass#92]
- [x] Add superadmins/admins as Houston admins automatically
- [x] Do not allow clients to see /admin
- [x] buttons (approve classes, fix delete items)
- [x] Google sign in on /admin
- [x] Flip between displaying users as IDs vs emails
- [x] Remove "change password" as accounts will be google only
- [x] Add empty collections
- [x] Retain Admin Hierarchy
- [x] Duplicate function
- [x] Filter
- [x] Add create admin functionality
- [x] Delete classes using server function

**Comment by ksjdragon** [comment]
Is this still prevalent with yogiben:Admin?

**Comment by yamanq** [comment]
some are still not supported

**Comment by ksjdragon** [comment]
The new error system says I'm unauthorized to complete this action, for approveClass()

**Comment by ksjdragon** [comment]
Can you write  "addAdmin" and "deleteAdmin" functions

**Comment by ksjdragon** [comment]
59781e390906f42efb968fa9ae85bded675519bf
